name: build_project
on: 
  push:
    branches:
      - ci-cd
jobs: 
  test:
   runs-on: ubuntu-latest
   steps:
   - name: update
     uses: appleboy/ssh-action@master
     with: 
         script: 
          cd ~/covid19-prediction && git pull
          cd ~/COVID-19 && git pull
          covid19-prediction/venv/bin/pip-sync
          echo "ACCESS_KEY_ID=${{ secrets.ACCESS_KEY_ID }}" > covid19-prediction/.env
          echo "SECRET_ACCESS_KEY_ID=${{ secrets.SECRET_ACCESS_KEY_ID }}" >> covid19-prediction/.env
          covid19-prediction/venv/bin/doit
         host: ${{ secrets.IP }}
         username:  ${{ secrets.USER }}
         password: ${{ secrets.PASSWORD }}
         port: 22







