name: build_project
on: 
  push:
    branches:
      - ci-cd
jobs: 
  test:
   runs-on: ubuntu-latest
   steps:
     - run: echo "So where are the server?"
       with: 
        ip: ${{ secrets.IP }}$
        username: ${{ secrets.USER }}$
        password: ${{ secrets.PASSWORD }}$
