name: build_project
on: 
  push:
    branches:
      - main
jobs: 
  run-pipeline:
   runs-on: ubuntu-latest
   steps:
   - name: update
     uses: appleboy/ssh-action@master
     with: 
         script:
          echo 'ACCESS_KEY_ID=${{ secrets.ACCESS_KEY_ID }}' > ~/covid19-prediction/.env
          echo 'SECRET_ACCESS_KEY_ID=${{ secrets.SECRET_ACCESS_KEY_ID }}' >> ~/covid19-prediction/.env
          echo 'DB=${{ secrets.DB }}' >> ~/covid19-prediction/.env
          cd ~/covid19-prediction && git pull && bash ./deploy.sh
         host: ${{ secrets.IP }}
         username:  ${{ secrets.USER }}
         password: ${{ secrets.PASSWORD }}
         port: 22
