name: build_project
on: 
  push:
    branches:
      - main
jobs: 
  run-pipeline:
   runs-on: ubuntu-latest
   steps:
   - name: update
     uses: appleboy/ssh-action@master
     with: 
         script: 
          cd ~/covid19-prediction && git pull && bash ./deploy.sh
         host: ${{ secrets.IP }}
         username:  ${{ secrets.USER }}
         password: ${{ secrets.PASSWORD }}
         port: 22
