name: build_project
on: 
  push:
    branches:
      - main
jobs: 
  run-pipeline:
   runs-on: ubuntu-latest
   steps:
   - name: update
     uses: appleboy/ssh-action@master
     with: 
         script:
          cd covid19-prediction && git pull &&
          echo 'ACCESS_KEY_ID=${{ secrets.ACCESS_KEY_ID }}' > .env &&
          echo 'SECRET_ACCESS_KEY_ID=${{ secrets.SECRET_ACCESS_KEY_ID }}' >> .env &&
          echo 'DB=${{ secrets.DB }}' >> .env &&
          source venv/bin/activate &&
          doit &
         host: ${{ secrets.IP }}
         username:  ${{ secrets.USER }}
         password: ${{ secrets.PASSWORD }}
         port: 22
